name: S.Arch
favicon: null
layout_spectrum: 0.19222443480975926
typography_spectrum: 0.7005398978944868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6269222432747483
  lightness: 0.332215468166396
  saturation: 0.9973052204586565
  rhythmicContrast: 0.39586080284789205
purpose: []
